---

state_selinux: "disabled"

install_packages:
  - vim
  - net-tools
  - bind-utils
  - yum-utils
  - policycoreutils-python
  - iptables-services
  - iptables-utils
  - tcpdump
  - nc
  - tree
  - curl
  - wget

stop_service:
  - NetworkManager.service
  - firewalld.service
